import { test, expect } from '@playwright/test';
test('parcours navigateur complet, rechargement, mobile et deuxième compte', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Heureux de vous revoir' })).toBeVisible();
  await page.screenshot({ path: '.local/screenshots/connexion.png', fullPage: true });
  await page.getByRole('link', { name: 'Créer un compte', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Créer mon espace' })).toBeVisible();
  await page.getByLabel('Adresse email').fill('browser-a@example.test');
  await page.getByLabel('Mot de passe').fill('Navigateur123!');
  await page.getByRole('button', { name: 'Créer mon compte' }).click();
  await expect(page.getByRole('heading', { name: 'Une chose à la fois.' })).toBeVisible();
  await page.getByRole('button', { name: 'Nouvelle tâche' }).click();
  await page.getByLabel('Titre', { exact: true }).fill('Préparer la soutenance');
  await page.getByLabel('Statut').selectOption('doing');
  await page.getByLabel('Échéance').fill('2026-10-12');
  await page.getByLabel('Description').fill('Revoir le parcours React → Express → MongoDB.');
  await page.getByRole('button', { name: 'Créer la tâche', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('créée');
  await page.reload();
  await expect(page.getByRole('button', { name: 'Consulter Préparer la soutenance' })).toBeVisible();
  await page.screenshot({ path: '.local/screenshots/taches-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Consulter Préparer la soutenance' }).click();
  await expect(page.getByText('Revoir le parcours React → Express → MongoDB.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Modifier', exact: true }).click();
  await page.getByLabel('Statut').selectOption('done');
  await page.getByLabel('Titre', { exact: true }).fill('Soutenance prête');
  await page.getByRole('button', { name: 'Enregistrer les modifications' }).click();
  await expect(page.getByRole('button', { name: 'Consulter Soutenance prête' })).toContainText('Terminée');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.local/screenshots/taches-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Consulter Soutenance prête' }).click();
  await page.getByRole('button', { name: 'Supprimer', exact: true }).click();
  await page.getByRole('button', { name: 'Annuler', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Soutenance prête', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Supprimer', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmer la suppression' }).click();
  await expect(page.getByRole('status')).toContainText('supprimée');
  await page.getByRole('button', { name: 'Nouvelle tâche' }).click();
  await page.getByLabel('Titre', { exact: true }).fill('Tâche privée A');
  await page.getByRole('button', { name: 'Créer la tâche', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Consulter Tâche privée A' })).toBeVisible();
  await page.getByRole('button', { name: 'Menu utilisateur' }).click();
  await page.getByRole('button', { name: 'Se déconnecter' }).click();
  await page.getByRole('link', { name: 'Créer un compte', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Créer mon espace' })).toBeVisible();
  await page.getByLabel('Adresse email').fill('browser-b@example.test');
  await page.getByLabel('Mot de passe').fill('Navigateur123!');
  await page.getByRole('button', { name: 'Créer mon compte' }).click();
  await expect(page.getByRole('heading', { name: 'Faites de la place à vos projets.' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Consulter Tâche privée A' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Menu utilisateur' }).click();
  await page.getByRole('button', { name: 'Se déconnecter' }).click();
  await page.getByLabel('Adresse email').fill('browser-a@example.test');
  await page.getByLabel('Mot de passe').fill('wrong-password');
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await page.getByLabel('Mot de passe').fill('Navigateur123!');
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Consulter Tâche privée A' })).toBeVisible();
});

test('navigation clavier, formulaire mobile et documentation Swagger', async ({ page }) => {
  await page.goto('/');
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'TaskFlow, accueil' })).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'Connexion', exact: true })).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'Inscription', exact: true })).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.getByLabel('Adresse email')).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.getByLabel('Mot de passe')).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('button', { name: 'Se connecter', exact: true })).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/api/docs/');
  await expect(page.getByRole('heading', { name: /TaskFlow API/ })).toBeVisible();
  await expect(page.getByRole('button', { name: /Authorize/ }).first()).toBeVisible();
});


test('routes directes, historique navigateur, formulaires et protection de session', async ({ page }) => {
  await page.goto('/tasks');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByRole('link', { name: 'Inscription', exact: true }).click();
  await expect(page).toHaveURL(/\/register$/);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Créer mon espace' })).toBeVisible();
  await page.goBack();
  await expect(page).toHaveURL(/\/login$/);
  await page.goForward();
  await expect(page).toHaveURL(/\/register$/);
  await page.getByLabel('Adresse email').fill('router@example.test');
  await page.getByLabel('Mot de passe').fill('RouterTest123!');
  await page.getByRole('button', { name: 'Créer mon compte', exact: true }).click();
  await expect(page).toHaveURL(/\/tasks$/);
  await page.goto('/login');
  await expect(page).toHaveURL(/\/tasks$/);
  await page.getByRole('button', { name: 'Nouvelle tâche' }).click();
  await page.getByLabel('Titre', { exact: true }).fill('Test formulaire');
  await page.getByRole('button', { name: 'Créer la tâche', exact: true }).click();
  await page.getByRole('button', { name: 'Consulter Test formulaire' }).click();
  await page.getByRole('button', { name: 'Modifier', exact: true }).click();
  await expect(page.getByLabel('Titre', { exact: true })).toHaveValue('Test formulaire');
  await page.getByRole('button', { name: 'Annuler', exact: true }).click();
  await page.getByRole('button', { name: 'Nouvelle tâche' }).click();
  await expect(page.getByLabel('Titre', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: 'Annuler', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Menu utilisateur' }).click();
  await page.getByRole('button', { name: 'Se déconnecter' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.goto('/tasks');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Adresse email').fill('router@example.test');
  await page.getByLabel('Mot de passe').fill('RouterTest123!');
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click();
  await expect(page).toHaveURL(/\/tasks$/);
  await page.evaluate(() => {
    const session = JSON.parse(sessionStorage.getItem('taskflow-session'));
    session.token = 'invalid.token.value';
    sessionStorage.setItem('taskflow-session', JSON.stringify(session));
  });
  await page.reload();
  await expect(page).toHaveURL(/\/login$/);
  await expect(page.getByRole('status')).toContainText('expiré');
});

test('page mon compte : consultation, modification du mot de passe et retour', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('link', { name: 'Créer un compte', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Créer mon espace' })).toBeVisible();
  await page.getByLabel('Adresse email').fill('account-test@example.test');
  await page.getByLabel('Mot de passe').fill('Navigateur123!');
  await page.getByRole('button', { name: 'Créer mon compte' }).click();
  await expect(page.getByRole('button', { name: 'Menu utilisateur' })).toBeVisible();

  await page.getByRole('button', { name: 'Menu utilisateur' }).click();
  await page.getByRole('button', { name: 'Mon compte' }).click();

  await expect(page).toHaveURL(/\/account$/);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Votre espace.' })).toBeVisible();
  await expect(page.locator('.account-meta strong')).toHaveText('account-test@example.test');

  await page.getByLabel('Mot de passe actuel').fill('Navigateur123!');
  await page.getByLabel('Nouveau mot de passe', { exact: true }).fill('NouveauPass123!');
  await page.getByLabel('Confirmer le nouveau mot de passe').fill('NouveauPass123!');
  await page.getByRole('button', { name: 'Modifier le mot de passe' }).click();
  await expect(page.getByRole('status')).toContainText('modifié');

  await page.getByRole('button', { name: '← Mes tâches' }).click();
  await expect(page.getByRole('heading', { name: 'Une chose à la fois.' })).toBeVisible();

  await page.getByRole('button', { name: 'Menu utilisateur' }).click();
  await page.getByRole('button', { name: 'Se déconnecter' }).click();

  await page.getByLabel('Adresse email').fill('account-test@example.test');
  await page.getByLabel('Mot de passe').fill('NouveauPass123!');
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Menu utilisateur' })).toBeVisible();
});


test('calendrier : densité, suivi, navigation, tâches sans date et mobile', async ({ page, request }) => {
  const registration = await request.post('/api/auth/register', { data: { email: 'calendar@example.test', password: 'Calendar123!' } });
  const session = await registration.json();
  const now = new Date();
  const prefix = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const headers = { Authorization: `Bearer ${session.token}` };
  for (let i = 0; i < 5; i++) {
    const response = await request.post('/api/tasks', { headers, data: { title: `Jour chargé ${i}`, status: 'todo', dueDate: `${prefix}-15` } });
    expect(response.ok()).toBe(true);
  }
  await request.post('/api/tasks', { headers, data: { title: 'Jour léger', status: 'doing', dueDate: `${prefix}-16` } });
  await request.post('/api/tasks', { headers, data: { title: 'Sans date', status: 'todo' } });
  await page.goto('/');
  await page.evaluate(session => sessionStorage.setItem('taskflow-session', JSON.stringify(session)), session);
  await page.goto('/tasks');
  await page.getByRole('button', { name: 'Calendrier', exact: true }).click();
  const busyDay = page.locator(`[data-date="${prefix}-15"]`);
  await expect(busyDay).toHaveClass(/density-4/);
  await expect(page.locator(`[data-date="${prefix}-16"]`)).toHaveClass(/density-1/);
  await expect(page.locator(`[data-date="${prefix}-17"]`)).toHaveClass(/density-0/);
  await busyDay.click();
  await expect(page.locator('.calendar-agenda')).toContainText('5 restante(s)');
  await page.getByRole('button', { name: 'Terminer', exact: true }).first().click();
  await expect(page.locator('.calendar-agenda')).toContainText('1 terminée(s)');
  await page.getByRole('button', { name: 'À reprendre', exact: true }).click();
  await expect(page.locator('.calendar-agenda')).toContainText('5 restante(s)');
  await page.getByRole('button', { name: 'Vue annuelle' }).click();
  await expect(page.locator('.calendar-heatmap .calendar-day')).toHaveCount(new Date(now.getFullYear(), 1, 29).getMonth() === 1 ? 366 : 365);
  await page.getByRole('button', { name: 'Année précédente' }).click();
  await expect(page.locator('.calendar-navigation h3')).toHaveText(String(now.getFullYear() - 1));
  await page.getByRole('button', { name: 'Aujourd’hui' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '.local/screenshots/calendrier-annuel-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Sans échéance (1)' }).click();
  await expect(page.locator('.calendar-agenda')).toContainText('Sans date');
  await page.getByRole('button', { name: 'Vue mensuelle' }).click();
  await page.setViewportSize({ width: 1280, height: 900 });
  await busyDay.click();
  await page.screenshot({ path: '.local/screenshots/calendrier-mensuel.png', fullPage: true });
  await page.locator('.agenda-title').first().click();
  await page.getByRole('button', { name: 'Modifier', exact: true }).click();
  await page.getByLabel('Échéance').fill(`${prefix}-16`);
  await page.getByRole('button', { name: 'Enregistrer les modifications' }).click();
  await expect(busyDay).toHaveAttribute('data-count', '4');
  await expect(page.locator(`[data-date="${prefix}-16"]`)).toHaveAttribute('data-count', '2');
});
